Add zipkin,kafka test cases
nginmesh/nginmesh pull request #54
Opened 2018-05-12 21:08 UTC by sakows

2018-05-14 17:01 UTC, sehz requested changes
remove .coverage file

2018-05-14 17:05 UTC, sehz requested changes

2018-05-14 17:05 UTC, sehyoc commented on istio/tests/cases/10_kafka_messages_spec.py
> +        expect(result).to(contain('MOCK_REQ_ID'))
I was expecting to see test key with value? so something like.
```expect(result.get('user-agent','MOCK_UserAgent'))```

2018-05-15 18:36 UTC, sehz requested changes

2018-05-15 18:36 UTC, sehz commented on istio/tests/cases/10_kafka_messages_spec.py
> +                print "Request to productpage did not found among messsages. Please, run test again."
if it is found, it should fail the test

2018-05-15 21:06 UTC, sakows commented
Update

2018-05-15 22:01 UTC, sehz approved these changes

2018-05-15 22:01 UTC, merged