Add mTLS Support
nginmesh/nginmesh pull request #63
Opened 2018-07-20 00:59 UTC by SirNexus

Added mTLS support for 0.7.1. Added configuration for TLS when ControlPlaneAuthPolicy is set to "MUTUAL_TLS".

2018-07-20 12:35 UTC, pleshakov requested changes
Please see my comments

2018-07-20 12:35 UTC, pleshakov commented on istio/agent/pilot/client.go
> +func ConfigureAuth(authPolicy string) *http.Client {
move `ConfigureAuth` and `GetEndpoint` to main.go

2018-07-20 12:35 UTC, pleshakov commented on istio/agent/pilot/client.go
> +			panic(fmt.Sprintf("Unknown auth policy: %v\n", authPolicy))
Why not glog.Fatal

2018-07-20 12:35 UTC, pleshakov commented on istio/agent/pilot/client.go
> +		return cfg
make `GetConfig()` return an error. In this case, you will have `return cfg, fmt.Errorf(...)`

in watcher.go https://github.com/nginxinc/nginmesh/blob/fix-mtls/istio/agent/pilot/watcher.go#L40 do not do deepequal if `w.client.GetConfig()` returns an error.

2018-07-20 16:23 UTC, SirNexus commented
I believe I addressed all of your suggestions. However, I'm wondering about the move of ConfigureAuth() and GetEndpoint() from client.go to main.go. In my mind, both of these functions are for configuring pilot communication and make sense inside of client.go. As well there are a lot of additional packages that are needed to make the functions work in main.go that are already utilized in client.go. Specifically, strings, ioutil and http.

2018-07-23 19:46 UTC, pleshakov approved these changes

2018-07-23 19:48 UTC, merged